services:
  MailSender:
    image: rexlee929/mailsender:latest
    container_name: sender
    restart: always
    ports:
      - "127.0.0.1:6003:80"
    environment:
      - AUTH_KEY=key
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      - MailSender
      
networks:
  MailSender:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "MailSender"
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1
